### ISSUE TITLE
Discussion: v2

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/homie#28]
What, I think, needs to be changed:

@marvinroger

* [x] Background:
  > An instance of a physical piece of hardware (an Arduino, an ESP8266...) is called a device. A device has attributes, like the current local IP, the Wi-Fi signal, etc. A device can expose multiple nodes.

I would talk about attributes after *devices*, *nodes*, *properties* are introduced. Therefore we can talk about attributes all at once.

* [x] Base:

I would make a "base" headline, where we talk about the root `homie/` topic and where we say that `Attributes are topics that are prefixed with a $.` 

* [x] Remove `$signal` and `$fw/versionchecksum`. This is implementation-specific, and can be sent to `$implementation/signal` and `$implementation/fwchecksum` if needed

* [x] Make the `$format` regex simple (without delimiter and flags)

* [x] Rename `$range` to `$array`

* [x] In the LED strip example, make all "array elements" share the same `datatype`, `format`, etc.

* [ ] Parsing tips for developers

* [ ] Web UI where we could create devices, nodes and properties and see the resulting MQTT messages, for reference

**Comment by marvinroger** [comment]
@euphi @kwave @ThomDietrich

**Comment by marvinroger** [comment]
Here's the WIP branch: https://github.com/marvinroger/homie/tree/redesign

What do you think?

**Comment by marvinroger** [comment]
We should also provide some parsing tips for developers. Ideally, we could also implement a simple Web UI where we could create devices, nodes and properties and see the resulting MQTT messages, for reference.

**Comment by ThomDietrich** [comment]
A few small details I'd like to mention:

* "Homie convention" - should the "C" be capitalized as in a keyword or lowercase because "Homie" is the brand and convention is just an addition to clarify the topic?

* `topic → "message"` or `topic ← "message"` are neat ways to indicate communication direction. However I fear that the meaning is not always clear. Especially as it depends on the perspective of a user. The IoT device developer might want to publish the `$nodes` topic while a client developer wants to subscribe to these. Hence:
  ```java
  IoT POV: homie/686f6d6965/$nodes ← "message"
  Client POV: homie/686f6d6965/$nodes → "message"
  ```

* I agree, we should give practical recommendations for developers of both worlds.

* We need one good example. I don't think "686f6d6965" is easy to comprehend and the LED example should rather be replaced by something related to the one example. How do you feel about discarding the weather station example. It has a few issues. Mostly numbers, no settable properties, it's boring 😄  Can you think of a good example. My coffee machine actually has almost everything we need (no array).

**Comment by marvinroger** [comment]
* I think "Homie Convention" is better, indeed

* Well, I we cannot cover both sides (a client and an IoT controller), because the document would be too heavy, right? It seems pretty obvious that if a device publishes to `$nodes`, a controller should instead subscribe to it.

* Definitely 😊

* I agree! What about a car?

```
Car
 - wheels node:
   - angle property (-45 to 45°)
 - engine node
   - speed property (0 to 50 km/h)
   - direction property (forward,backward)
- lights array node ([0-1] (0 front light, 1 back light)
   - intensity (0 to 100 %)
   - color (color, RGB)
```

This is obviously a simplified car (an engine cannot be set to "50km/h"), but I think it works pretty well.
