### ISSUE TITLE
Comments after using

### ISSUE THREAD

**Issue by cranphin** [marvinroger/homie#4]
Hi!

This issue is mainly here to see what your thoughts are on some points which occurred to me while implementing this scheme. I quite like the idea, I can see this getting some momentum someday ;)
- You seem to have considered some auto detection for nodes, by providing the $nodes device property. But the one thing I can't find out that way (nor any other) is which node is settable. Do you think there might be benefit to adding a way to determine that by inspection?
- You don't mention any QoS or retention policy for node properties (and their setters!) would they normally be retained or not, or is that a case by case decision? Same for QoS. I assume you've thought about that, it would be nice to have a note in the readme. (Actually, suggested QoS for device properties would be nice too)
- You have a $uptime device property. It would be nice to have a suggestion how to handle that one, do you normally update it every second, every minute? Both could cost resources on a small device. If a controller doesn't know the policy it doesn't know how far our the time is.
- It would be nice to have a policy for 'on demand' values. For example I like to let the controller decide when to check temperature. It would make something like the $uptime easier/more reliable to, you ask for a time when you want to know it, when you get it it will be pretty much accurate.

Just thoughts :)

Cheers!

**Comment by marvinroger** [comment]
Hi!

So sorry for the delay, I missed the notification or something...

* This is an hard one, because nodes aren't actually settable, node properties are. So each node would have to list every single property and if its settable or not. Basically yes, introspection, which would be great as a backend would then be able to know how to communicate with a device without knowing how it works in the first place. The question is how to implement it? Subtopics? I would like to have your opinion about it. :)

* QoS 1 all the way, it ensures the messages get delivered, and duplication is not a problem since Homie is state-based. Regarding the retention policy for node properties and their setters, I was wondering if we should mention messages should be retained (since I don't see any use case where it should not)... So yes, you're right, let's mention it in the convention!

* Nice point. What about `$uptime/interval` (in seconds) and `$uptime/value` (in seconds)? So each device could pick its optimal interval time. This is a breaking change, but at this point this is not too much of an issue.

* RPC is something we've discussed before with @jpmens and we thought it would be a pity to implement it upon MQTT. But maybe we could think in terms of `commands` which updates a `state` rather than a `request` that results in a `response`. What do you think?

**Comment by marvinroger** [comment]
See the [v2](https://github.com/marvinroger/homie/tree/v2) branch and let's work on it! :wink:

**Comment by stufisher** [comment]
Sorry i had not spotted this discussion over here. Good question about implementation. Briefly thinking something like:
`devices/deviceid/temperature/$properties unit:gettable, temperature:gettable, offset:settable`
might work. I will try and have a bit more of a think about it :)

**Comment by marvinroger** [comment]
No problems!

Let's consider a device `deviceid` which exposes a single `thermostat1` node of type `thermostat`. It has two properties: an `unit` one which is not settable, and a `temperature` one which is settable

Then, instead of the current:

* `devices/deviceid/$nodes` → `thermostat1:thermostat`

We could do:

* `devices/deviceid/thermostat1/$type` → `thermostat`
* `devices/deviceid/thermostat1/$properties` → `unit,temperature:settable`

So the current `$nodes` would disappear, it feels cleaner this way. What do you think?

**Comment by stufisher** [comment]
That looks pretty good, and yes $nodes could be deprecated as its becomes duplication.

**Comment by marvinroger** [comment]
Most of the above have been implemented in the v2 (and redesign) branch. 😉
